CREATE TABLE IF NOT EXISTS TUTOR (
    id_tutor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_identidad VARCHAR(20),
    nombre VARCHAR(100),
    telefono VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS MASCOTA (
    id_mascota INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tutor INT,
    nombre VARCHAR(50),
    especie VARCHAR(50),
    sexo VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS NIVEL_PRIORIDAD (
    id_prioridad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_prioridad VARCHAR(50),
    nivel INT,
    color_identificador VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS PERSONAL_MEDICO (
    id_medico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento_identidad VARCHAR(20),
    nombre VARCHAR(100),
    rol VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS TURNO (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_turno VARCHAR(20),
    id_mascota INT,
    id_prioridad INT,
    id_medico INT,
    fecha DATE DEFAULT CURRENT_DATE,
    hora TIME DEFAULT CURRENT_TIME,
    estado VARCHAR(30)
);

-- Registros reales de prueba
INSERT INTO TUTOR (documento_identidad, nombre, telefono) VALUES ('1017000111', 'Carlos Perez', '3001234567');
INSERT INTO TUTOR (documento_identidad, nombre, telefono) VALUES ('1020304050', 'Maria Rodriguez', '3119876543');

INSERT INTO MASCOTA (id_tutor, nombre, especie, sexo) VALUES (1, 'Rocky', 'Canino', 'Macho');
INSERT INTO MASCOTA (id_tutor, nombre, especie, sexo) VALUES (2, 'Mimi', 'Felino', 'Hembra');

INSERT INTO NIVEL_PRIORIDAD (nombre_prioridad, nivel, color_identificador) VALUES ('Urgencia', 1, 'Rojo');
INSERT INTO NIVEL_PRIORIDAD (nombre_prioridad, nivel, color_identificador) VALUES ('Consulta General', 3, 'Verde');

INSERT INTO PERSONAL_MEDICO (documento_identidad, nombre, rol) VALUES ('987654321', 'Dra. Laura Gomez', 'Veterinario');
INSERT INTO PERSONAL_MEDICO (documento_identidad, nombre, rol) VALUES ('123456789', 'Dr. Andres Restrepo', 'Veterinario');

INSERT INTO TURNO (codigo_turno, id_mascota, id_prioridad, id_medico, estado) VALUES ('T-001', 1, 1, 1, 'En espera');
INSERT INTO TURNO (codigo_turno, id_mascota, id_prioridad, id_medico, estado) VALUES ('T-002', 2, 2, 2, 'Atendiendo');
